<a href="https://colab.research.google.com/github/Syeddaniel711/Notes/blob/main/NumPy_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import os

In [ ]:
#How to make an array=(2,3,3) 1-D
one_D = np.array([2,3,3])
print(one_D)

[2 3 3]


In [ ]:
#How to make two dimensional array = (2,3,4),(2,4,5) 2-D
two_D = np.array([[2,3,4],[2,4,5]])
print(two_D)

[[2 3 4]
 [2 4 5]]


In [ ]:
#In additional, An array also can specify type
one_D_16=np.array([2,3,3],dtype='int16')

In [ ]:
#Get Dimension of array
np.ndim(two_D)   #should to because is two dimensional array 2-D

2

In [ ]:
#Shape of Array (Row x Column)
np.shape(two_D)

(2, 3)

In [ ]:
# Get Types
two_D.dtype

dtype('int32')

In [ ]:
one_D_16.dtype

dtype('int16')

In [ ]:
#Get item size
one_D_16.itemsize

2

In [ ]:
#Get total size
one_D_16.nbytes

6

## Accessing / Changing Specific Elements, rows, columns, etc


In [ ]:
data=np.array([[2,3,5,4,5,5,10],[3,4,5,4,5,6,7]])
data.shape

(2, 7)

In [ ]:
# Get A specific Elements (10)
# Additonal notes, row and column will began with zero
data[0,6]

10

In [ ]:
# Get a specific row(We want the first row)
data[0, ]

array([3])

In [ ]:
#Get a specific row and value(we want row 2 with three to 6)
data[1,0:6]

array([3, 4, 5, 4, 5, 6])

In [ ]:
#Get a specific colum(10,7)
data[:,6]

array([10,  7])

In [ ]:
#Getting a little more fancy [startindex:endindex:stepsize]
# Lets say we want every leap 2,5,5
data[0,0:5:2]

array([2, 5, 5])

In [ ]:
#if we want change value inside with specific row [row 1 , 4=99]
data[0,3]=99
print(data)
print("--------------------------------------------")
#if we want change value inside with specific column[column 3, 5=0,5=2]
data[:,2]=[0,2]
print(data)

[[ 2  3  0 99  5  5 10]
 [ 3  4  2  4  5  6  7]]
--------------------------------------------
[[ 2  3  0 99  5  5 10]
 [ 3  4  2  4  5  6  7]]


In [ ]:
# 3-D example
Three_D =np.array([[[7,2],[4,6]],[[2,3],[3,5]]])
print(Three_D)

[[[7 2]
  [4 6]]

 [[2 3]
  [3 5]]]


In [ ]:
# Get a Specific elementn(work outside in) 4
Three_D[0,1,0]

4

In [ ]:
# Get a Specific element( first row)
Three_D[0,:,:]

array([[7, 2],
       [4, 6]])

In [ ]:
#Get a specific row (7,4,2,3)
Three_D[:,0,:]


array([[7, 2],
       [2, 3]])

In [ ]:
# replace specific value
Three_D[0,1,:]=[999,666]
Three_D[1,1,0]=999
print(Three_D)

[[[  7   2]
  [999 666]]

 [[  2   3]
  [999   5]]]


##  Initializing Different Types of Arrays


In [ ]:
#All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#All 1s matrix #
a=np.ones((2,3,3))

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

In [ ]:
#Any other number
np.full((2,2),666)

array([[666, 666],
       [666, 666]])

In [ ]:
# Any other number (full_like)
np.full_like(Three_D,4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [ ]:
# Random decimal numbers
np.random.rand(4,2)

In [ ]:
#Random Integer Values
np.random.randint(4,7 ,size=(10,3))

array([[6, 6, 4],
       [5, 6, 5],
       [6, 6, 5],
       [5, 4, 5],
       [6, 6, 4],
       [6, 6, 4],
       [6, 4, 5],
       [5, 5, 6],
       [4, 4, 4],
       [6, 4, 4]])

In [ ]:
#The identify matriz
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#repeat an array and make print every row
arr =np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
output=np.ones((5,5))
print(output)
print("------------------")
z= np.zeros((3,3))
z[1,1]=9
print(z)
print("------------------")
output[1:4,1:4] =z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
------------------
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
------------------
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Mathematics

In [ ]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
#Addition
a+2

array([3, 4, 5, 6, 7])

In [ ]:
#Subtraction
a-10

array([-9, -8, -7, -6, -5])

In [ ]:
#Divide
a/10

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [ ]:
#Mutiply
a*2

array([ 2,  4,  6,  8, 10])

In [ ]:
#Square
a**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [ ]:
# cos sin tan
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

### Linear Algerbra

In [ ]:
a =np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)


[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [ ]:
#Find the determine
c =np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
#Determinant

In [ ]:
#Trace

In [ ]:
#inverse


### Statistics


In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# the small value in the array
np.min(stats)

1

In [ ]:
#THe biggest value for every row
np.max(stats,axis=1)

array([3, 6])

In [ ]:
#sum all
np.sum(stats)

21

In [ ]:
# sum per axis
np.sum(stats , axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [ ]:
before = np.array([[1,2,3,4],[6,7,8,9]])
print(before)
after = before.reshape(1,8)
print(after)

[[1 2 3 4]
 [6 7 8 9]]
[[1 2 3 4 6 7 8 9]]


In [ ]:
# vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.hstack((v1,v2))


array([1, 2, 3, 4, 5, 6, 7, 8])

### Miscellaneous

In [ ]:
os.getcwd()

'C:\\Users\\LENOVO'

In [ ]:
#Load data from file
filedata=np.genfromtxt('data1.txt',delimiter=',')
filedata=filedata.astype('int32')
filedata

array([     2,      3,      4,      5,      6,      7,      7,      7,
           88,      3,     56,      3,      2,      4,      6,      2,
            5,      2,    623,      5,      2,      5,    226,      2,
          525,     52,  53252,      5,      2,     52, 532523,      5,
          235,     25,      4,    525])

### Boolean Masking and Advanced Indexing

In [ ]:
#show true or false the value in array that more than 10
filedata>10

array([False, False, False, False, False, False, False, False,  True,
       False,  True, False, False, False, False, False, False, False,
        True, False, False, False,  True, False,  True,  True,  True,
       False, False,  True,  True, False,  True,  True, False,  True])

In [ ]:
#show the number that more than 10
filedata[filedata>10]

array([    88,     56,    623,    226,    525,     52,  53252,     52,
       532523,    235,     25,    525])

In [ ]:
#You can index with a list in NumPy


In [ ]:
#if any value in by column more than 8
a=np.array([[1,2,34,5,6,7,8,8,78],[1,2,3,66,7,8,9,99,9]])
np.any(a>8,axis=0)

array([False, False,  True,  True, False, False,  True,  True,  True])

In [ ]:
#Quiz
a=np.arange(30).reshape(6,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
#select number(10,11,15,16)
a[2:4,0:2]

array([[10, 11],
       [15, 16]])

In [ ]:
#select number(1,7,13,19)
a[[0,1,2,3],[1,2,3,4]]

array([ 1,  7, 13, 19])

In [ ]:
#select number(3,4,23,24,29,30)
a[[0,4,5],3:]

array([[ 3,  4],
       [23, 24],
       [28, 29]])